python -W ignore python/flashGGAnalyzer.py analysis_cfgs/signal_hhhTo4b2g.cfg   > logs/signal_hhhTo4b2g.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/diphotonInclusive.cfg  > logs/diphotonInclusive.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/diphotonJetBox1.cfg  > logs/diphotonJetBox1.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/diphotonJetBox2.cfg > logs/diphotonJetBox2.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/recoAnalyzer.cfg > logs/data.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/TGJets.cfg > logs/TGJets.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/TTGG.cfg > logs/TTGG.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/TTGJets.cfg > logs/TTGJets.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/photonInclusive20To40.cfg > logs/photonInclusive20To40.log &
python -W ignore python/flashGGAnalyzer.py analysis_cfgs/photonInclusive40ToInf.cfg > logs/photonInclusive40ToInf.log &
